apiVersion: v1
kind: Pod
metadata:
  name: mc-restore-helper
  namespace: games
spec:
  containers:
    - name: helper
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: minecraft-data
