apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-usb-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: usb-storage
  local:
    path: /var/mnt/minecraft-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - talos-5mg-hse
