apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Mi
