apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: minecraft
  selector:
    app: minecraft
